# Gradle
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.tooling.parallel=true
org.gradle.warning.mode=all

# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx2048M

# Android
android.enableJetifier=false
android.nonFinalResIds=true
android.nonTransitiveRClass=true
android.defaults.buildfeatures.resvalues=false
android.defaults.buildfeatures.shaders=false

# Dokka
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true

# Publishing
GROUP=io.github.zed-alpha.shadow-gadgets
VERSION_NAME=2.5.1

POM_URL=https://github.com/zed-alpha/shadow-gadgets/
POM_INCEPTION_YEAR=2022

POM_LICENSE_NAME=The MIT License
POM_LICENSE_URL=https://opensource.org/license/mit
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/zed-alpha/shadow-gadgets/
POM_SCM_CONNECTION=scm:git:git://github.com/zed-alpha/shadow-gadgets.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com:zed-alpha/shadow-gadgets.git

POM_DEVELOPER_ID=zed-alpha
POM_DEVELOPER_NAME=zed-alpha
POM_DEVELOPER_URL=https://github.com/zed-alpha/

mavenCentralPublishing=true
mavenCentralAutomaticPublishing=true
signAllPublications=true

enablePublishing=true